name: Documentation
on:
    push:
        branches: [ main ]
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build Docs
          run: npm run docs
        - name: Deploy Docs
          run: |
            echo $GH_TOKEN
            git config --global user.email 'musaharoon.2003@gmail.com'
            git config --global user.name 'musa'
            npm run deploy-docs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}