name: Documentation
on:
    push:
        branches: [ main ]
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build Docs
          run: npm run docs
        - name: Config Email
          run: git config --global user.email "musaharoon.2003@gmail.com"
        - name: Config Name
          run: git config --global user.name "Musa"
        - name: Deploy Docs
          run: npm run deploy-docs