name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm test
    - name: Init lint
      run: npm run lint:init
    - name: Run linting
      run: npm run lint
