name: Scheduled Tasks
on:
    schedule:
        - cron: '0 0 * * *'
jobs:
    tasks:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Tasks
          run: npm run tasks