name: Custom Workflow
on:
    push:
        branches: [ main ]
jobs:
    custom:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Custom Task
          run: npm run custom-task